name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Ensure we're using the latest version

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Replace API key in HTML file
      run: |
        sed -i "s/REPLACE_WITH_API_KEY/${{ secrets.MAP_API_KEY }}/g" map.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Ensure we're using the latest version
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # The directory to publish
